
version: 2

models:
  - name: stg_users
    description: data on users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
  - name: stg_addresses
    description: data on user addresses
    columns:
      - name: address_id
        tests:
          - not_null
          - unique
  - name: stg_events
    description: data on application events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
    tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list: [session_id, event_id]
          ignore_row_if: any_value_is_missing 
  - name: stg_order_items
    description: data on order quantities
    columns:
      - name: order_id
        tests:
          - not_null
  - name: stg_orders
    description: data on orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
  - name: stg_products
    description: data on products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
  - name: stg_promos
    description: data on product promos
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique
