
version: 2

models:
  - name: users
    description: data on users
  - name: addresses
    description: data on user addresses
  - name: events
    description: data on application events
  - name: order_items
    description: data on order quantities
  - name: orders
    description: data on orders
  - name: products
    description: data on products
  - name: promos
    description: data on product promos